// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3uJIKk5uX1gfISqm0OK8zGiRo9L_x-MU',
    appId: '1:167730598631:web:a134159ee6c2ddb2d94842',
    messagingSenderId: '167730598631',
    projectId: 'todolist2-e7b3d',
    authDomain: 'todolist2-e7b3d.firebaseapp.com',
    storageBucket: 'todolist2-e7b3d.firebasestorage.app',
    measurementId: 'G-5YDKT31L87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjvLKU92PMewnzHfDup-MiuTECJYFTbuY',
    appId: '1:167730598631:android:96c5cf94ce2a1d9bd94842',
    messagingSenderId: '167730598631',
    projectId: 'todolist2-e7b3d',
    storageBucket: 'todolist2-e7b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSppTY6yr8ZhmIYmavHTAEdFpUm-kktL8',
    appId: '1:167730598631:ios:fe4e4f3062d9f8e8d94842',
    messagingSenderId: '167730598631',
    projectId: 'todolist2-e7b3d',
    storageBucket: 'todolist2-e7b3d.firebasestorage.app',
    iosBundleId: 'com.example.todoList2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSppTY6yr8ZhmIYmavHTAEdFpUm-kktL8',
    appId: '1:167730598631:ios:fe4e4f3062d9f8e8d94842',
    messagingSenderId: '167730598631',
    projectId: 'todolist2-e7b3d',
    storageBucket: 'todolist2-e7b3d.firebasestorage.app',
    iosBundleId: 'com.example.todoList2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3uJIKk5uX1gfISqm0OK8zGiRo9L_x-MU',
    appId: '1:167730598631:web:491db8b5542d5f00d94842',
    messagingSenderId: '167730598631',
    projectId: 'todolist2-e7b3d',
    authDomain: 'todolist2-e7b3d.firebaseapp.com',
    storageBucket: 'todolist2-e7b3d.firebasestorage.app',
    measurementId: 'G-KF73NNFE4E',
  );
}
